name: Build and Deploy

on:
  push:
    branches:
    - main
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install and Build   
        run: |
          npm install
          npm run docs:build
      - name: Deploy (main)
        # On main branch
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/.vitepress/dist
      - name: Deploy (preview)
        # if this build is a PR build and the PR is NOT from a fork
        if: github.event_name == 'pull_request' && github.repository == github.event.pull_request.head.repo.full_name 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/.vitepress/dist
          target-folder: "previews/PR${{ github.event.number }}"
